### ISSUE TITLE
pip install NameError: global name 'chain' is not defined

### ISSUE THREAD

**Issue by calebcase** [ionelmc/python-hunter#20]
Pip install fails due to undefined `chain`:

```
root@f0353c8a6727:/# pip install hunter
Downloading/unpacking hunter
  Downloading hunter-1.0.1.tar.gz (187kB): 187kB downloaded
  Running setup.py (path:/tmp/pip_build_root/hunter/setup.py) egg_info for package hunter
    
<snip>

Copying src/hunter.egg-info to /usr/local/lib/python2.7/dist-packages/hunter-1.0.1.egg-info

running install_scripts

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/hunter/setup.py", line 179, in <module>

    for path in glob(join(root, '*.pyx' if Cython else '*.c'))

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 53, in run

    return _install.run(self)

  File "/usr/lib/python2.7/distutils/command/install.py", line 620, in run

    outputs = self.get_outputs()

  File "/usr/lib/python2.7/distutils/command/install.py", line 663, in get_outputs

    for filename in cmd.get_outputs():

  File "/tmp/pip_build_root/hunter/setup.py", line 77, in get_outputs

    return chain(install_lib.get_outputs(self), self.outputs)

NameError: global name 'chain' is not defined

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/hunter/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-OqoeOx-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/hunter
Storing debug log for failure in /root/.pip/pip.log
```

Appears to have been broken in commit 67ac216fc6dcb3e39b789704f4d12a5be8f3cde7.

**Comment by ionelmc** [comment]
Fixed in https://github.com/ionelmc/python-hunter/commit/1a950cb8d417fdca4933ee9df37b35fc11ca3ee6 ... gonna make a new release soon.

**Comment by ionelmc** [comment]
Ok, there's 1.0.2 on pypi, windows wheels are going in later.

**Comment by calebcase** [comment]
Thanks!
